import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import "@payloadcms/next/css";

import type { ReactNode } from "react";

import { RootLayout as PayloadRootLayout } from "@payloadcms/next/layouts";

import { payloadConfigPromise } from "@/lib/payloadConfig";
import { payloadServerFunction } from "@/lib/payloadServerFunction";
import { importMap } from "./(payload)/admin/importMap.js";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Avec Toi",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    // App root layout:
    // - global CSS + fonts
    // - wraps the app with Payload's Next.js RootLayout (admin + server functions wiring)
    return (
        <PayloadRootLayout
            config={payloadConfigPromise}
            htmlProps={{
                lang: "en",
                className: `${geistSans.variable} ${geistMono.variable} h-full antialiased`,
            }}
            importMap={importMap}
            serverFunction={payloadServerFunction}
        >
            {children}
        </PayloadRootLayout>
    );
}
